### ISSUE TITLE
showRewardVideoAd() not working

### ISSUE THREAD

**Issue by mujaffars** [floatinghotpot/cordova-admob-pro#462] opened 2016-09-23 09:10 UTC
For interstitial and banner I am using

`AdMob.showInterstitial();`
`AdMob.showBanner(getSelectedPosition());`
is working correctly. Now I am trying to display the Reward video. Firstly I have prepared the Reward video by

`AdMob.prepareRewardVideoAd({adId: admobid.reward, autoShow: false});` 

Then I am trying to show it
`AdMob.showRewardVideoAd();`

In documentation I have not found any method as AdMob.showRewardVideoAd().

What is the correct method, How should I display it ? please help

**Comment by happinesssam** [comment] 2016-09-29 23:12
I have been butting my head on this issue as well, and I might have something.

First, are you trying to publish to Android? Because I think there is a bug in the javascript in the admobExport.prepareRewardVideoAd function if you pass an object as the parameter.

The java function only takes an adId string as the parameter. If you pass an object to it it extracts the success and error functions out of it and uses them and passes other values into an options object. If you pass a string it creates an adId value on the options object using the string you passed. It then discards the options object and just uses the parameter you passed as the adId, so if you passed an object I would expect it to fail (unless I am missing something). Did you try just passing a string to AdMob.prepareRewardVideoAd?

**Comment by happinesssam** [comment] 2016-09-30 23:38
Just an update, it turns out I had it the wrong way round - it's when you just pass the adId as a string that it doesn't work, though whether that would be considered a bug or just confusing documentation I'm not sure.

When I passed an object with an adId property it seems to go ok, though now I'm getting a 'No fill' error, but that's a problem with my mediation setup.

**Comment by floatinghotpot** [comment] 2016-10-05 02:16
Please see the javascript APIs defined here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/www/AdMob.js

**Comment by happinesssam** [comment] 2016-10-05 11:07
Go to admobExport.prepareRewardVideoAd. If you pass just the adId as a string (as I tried to do initially) it will add adId to the options object. It doesn't use options object, it just passes arg, which in this case is a string, so GenericAdPlugin is throwing errors.

**Comment by mujaffars** [comment] 2016-10-05 12:34
The reward video is displaying fine first time, But when again I try to `AdMob.prepareRewardVideoAd({adId: admobid.reward, autoShow: false});` and show it `AdMob.showRewardVideoAd();`, Nothing is happening.

**Comment by mrkaratechamp** [comment] 2017-01-03 03:13
I have your same problem,  I can do mediation correct with vungle, charboost and unity ads, (still can't  get any ads from adcolony, so I don't now if its ok), but the problem is this only work one time, the success callback from prepareRewardVideoAd give me an OK, and the parameters sends ok , and all goes ok to the exec function, but simply the callback from the plugin module jar, doent't fire, no error on android console, no error at all, so really don't know what's going on, please just give us at least an status, or at least a clue where the error can be.

thanks!

**Comment by floatinghotpot** [comment] 2017-03-16 17:29
Now it's fixed in cordova-plugin-admobpro@2.28.3, as described in #495.

**Closed by floatinghotpot** 2017-03-16 17:29 UTC
