### ISSUE TITLE
ads not showing in Windows Phone 8.1

### ISSUE THREAD

**Issue by budiselic** [floatinghotpot/cordova-admob-pro#84] opened 2015-02-12 12:17 UTC
Hi, 

I am struggling now for days to makes tihs work on WP 8.1.
I developed small simple html5 game and used PhoneGap Build to make android, ios and wp files.

Ads are showing nice on android and ios, but not in windows phone 8.1.

I took described steps for phonegap buils several times and I dont know where I make mistake, if i do one.

This is part of js code:
```javascript
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = {
        banner: 'ca-app-pub-xxxxx/eeeee',
        interstitial: 'ca-app-pub-xxxxx/rrrrr'
    };
}
else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = {
        banner: 'ca-app-pub-xxxxx/zzzzz',
        interstitial: 'ca-app-pub-xxxxx/hhhhh'
    };
}

else {
    admobid = {
        banner: 'ca-app-pub-xxxxx/kkkkk',
        interstitial: 'ca-app-pub-xxxxx/yyyyy'
    };
}

function onDeviceReady() {
AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );
if(AdMob) AdMob.showInterstitial();
}

function onLoad() {
	document.addEventListener('deviceready', onDeviceReady, false);
}
```
and on body element i have onload="onLoad()"

Does windows phone 8.1 needs some special permission in config.xml to work?

**Comment by andrequintino** [comment] 2015-02-14 23:15
I'm having the same problem. All works fine on IOS and Android, but on WP8.1 not.

**Comment by andreszs** [comment] 2015-02-15 02:42
I have exactly the same problem, nothing is shown under WP 8.1 when compiling with CLI 4.2.0. Maybe it only works with Cordova 3.6.3? That would be disastrous, as Cordova 4.2 fixed many bugs from 3.6.

The developers have nothing to say about this? Should I buy a support license?

**Comment by mobilino** [comment] 2015-02-16 19:13
I have exactly the same problem too. iOS and Android are working perfectly, nothing shows using WP 8.1.
I use Phonegap Build with 3.6.3.

**Comment by andrequintino** [comment] 2015-02-24 22:04
Looking at the source code of AdMob, I found this line:
cordova.exec( successCallback, failureCallback, 'AdMob', 'createBanner', [ options ] );

But the name of C# class is AdMobPlugin.

In Cordova documentation, there is the following information:
"This class name must exactly match what you call specify as the service in the cordova.exec() call on the JavaScript side".

Please, am I correct? There are someone that can change this code?

**Comment by floatinghotpot** [comment] 2015-02-25 13:42
I've merged the code from dbaseman and did some bugfix. it's build pass with a demo project with phonegap build service, but not tested on device yet. 

could you please help to verify the plugin wp8 code?

**Comment by budiselic** [comment] 2015-02-25 21:11
It appears to work now on wp8.1, i will do more tests :)

**Comment by budiselic** [comment] 2015-02-26 09:37
I tested on several windows pohne 8.1 devices and it works now. 

But there is a little problem with banners, it apears that banner overlap content, for example in android it doesn't. I use bottom center banner position, and I have one button at the same position in my application and then banner overlap it. On android every thing ok.

Can this be fixed also? :)

**Comment by AlexB71** [comment] 2015-02-26 11:03
I've tried wp8 and find the banners are not changing there is no way to request a new banner too.

**Comment by vpease** [comment] 2015-02-26 15:38
In my case, its not working. Updated to the last code.
if (AdMob) {
                        console.log('AdMob SI esta');
                        AdMob.createBanner({adId: result.banner,adSize: AdMob.SMART_BANNER,
                            position: AdMob.AD_POSITION.BOTTOM_CENTER,autoShow: true,isTesting: true});
                        AdMob.prepareInterstitial({adId: result.interstitial,isTesting: true,
                            autoShow: false});
                        AdMob.showInterstitial();
                    }

**Comment by andrequintino** [comment] 2015-02-26 18:45
The banner is showing ok, but when I execute the command AdMob.showInterstitial(); the app close.

**Comment by budiselic** [comment] 2015-02-26 21:46
well, when I execute the command AdMob.showInterstitial(); the app close also too. But I then tried to prepare interstitial and that show it after some time, then works.

**Comment by budiselic** [comment] 2015-02-27 08:07
another problem, ads dont show up when app put on windows phone marketplace. When it need to show interstital just exits the app.

**Comment by andreszs** [comment] 2015-02-28 02:27
I updated the src/wp8 files, and the plugin.xml file, and ads are still not showing. In fact I still see no difference at all from the previous plugin.

**Comment by vpease** [comment] 2015-02-28 05:37
Using Ionic. this procedure worked for me:

- remove the wp8 platform: ionic platform rm wp8
- remove the plugin: ionic plugin rm com.google.cordova.admob
- add the plugin using the git url: ionic plugin add https://github.com/floatinghotpot/cordova-admob-pro
- add the platform wp8: ionic platform wp8

Now both banner and intersitial are  working fine. 

My only problem now is that banner is always overlapping the webview instead of resize the screen in portrait. In landscape the banner is smart enough to avoid the overlap. This is an old issue.

**Comment by budiselic** [comment] 2015-03-03 14:31
at once banners and interstitials on wp8.1 not showing anymore.

did you change something? because i didnt work anything on my app since last time when it was working

**Comment by dmotion** [comment] 2015-03-03 18:37
I can confirm the ads are not showing up in my WP-apps as well (since about one day).

I didn't change anything in the code - they're just not showing up.

No events are triggered, so the ad is not loaded and is not giving any errors - it's just a black and empty space...

**Comment by floatinghotpot** [comment] 2015-03-04 10:37
i see some wp8 banner ad today. maybe something is wrong with the google ad service occasionally.

could you check and update your status?

**Comment by dmotion** [comment] 2015-03-04 10:45
I can confirm that the ads are showing allright with the WP version of your excellent plugin.

They dissapereared for about one / two days (without notice / doing anything from my side) and the came back in the same way... I guess it's a Google thing.

Occasionally even the Android version is not showing ads, but when I reload my app and wait for about 30 secs it's showing ads already.

**Comment by kimras** [comment] 2015-04-22 08:51
I am using Phonegap build and can not get the WP 8.1 to show. iOS and Android is fine.
Is it becaurse I use the plugin from thes cordova repository or are ther something special to do to the WP to work, other than registering on admob and include the plugin?

**Comment by floatinghotpot** [comment] 2015-09-10 06:39
I verified this plugin on a Lumia windows phone and prove it works, so I will close this issue.

**Closed by floatinghotpot** 2015-09-10 06:39 UTC

**Comment by kimras** [comment] 2015-09-10 09:34
I agree, it works fine. And I actually gets more money back per usage with this on than on Android and iPhone. So i will be looking for updating the plugin's on thews platforms as well.

**Comment by ramu14321** [comment] 2015-09-20 19:21
This plugin not at all working in windows phone 8.1, I tested in my new Microsoft Lumia540, this plugin having problem only for windows i wasted my lot of valuble time  due  to this no solution found yet to display adds in windows  platform.

**Comment by floatinghotpot** [comment] 2015-09-21 02:19
a few days ago, I tested it in m lumia phone and it works fine.

how did you test?

try create a new project, add platform wp8, add plugin, copy the 2 files from {plugin}/test/ to your www/, then build and run.

**Comment by ramu14321** [comment] 2015-09-21 05:40
Hi thanks for your prompt response,In the early morning IST time when I wake up I tried your above solution you suggested,I created new project added wp8 platform added plugin and built and run on my Microsoft Lumia540 every thing fine till here,but when i click on show banner or show Interstitial my app getting crashed,Here is the stack trace i collected while i am debugging from Visual Studio
For Banner 
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Element is already the child of another element.
  Source=System.Windows
  StackTrace:
       at MS.Internal.XcpImports.CheckHResult(UInt32 hr)
       at MS.Internal.XcpImports.Collection_AddValue[T](PresentationFrameworkCollection`1 collection, CValue value)
       at MS.Internal.XcpImports.Collection_AddDependencyObject[T](PresentationFrameworkCollection`1 collection, DependencyObject value)
       at System.Windows.PresentationFrameworkCollection`1.AddDependencyObject(DependencyObject value)
       at System.Windows.Controls.RowDefinitionCollection.AddInternal(RowDefinition value)
       at System.Windows.PresentationFrameworkCollection`1.Add(T value)
       at Cordova.Extension.Commands.AdMob.__showBannerSplit(Grid grid, CordovaView view, Int32 position)
       at Cordova.Extension.Commands.AdMob.<__showBanner>b__74_0()
  InnerException: 

For Interstitial
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=GoogleAds
  StackTrace:
       at A.c81d6e02e9732689b8a214cc526c72649.c8b6f578dd247fa29b178e585ca8da582()
       at GoogleAds.InterstitialAd.ShowAd()
       at Cordova.Extension.Commands.AdMob.<__showInterstitial>b__79_0()
  InnerException: 

System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Windows.ni.dll
Additional information: Exception has been thrown by the target of an invocation.
So please look into these issues and help me out addmob working for me as i am facing no revenue days for  my windows phone apps.
![admob_banner_error](https://cloud.githubusercontent.com/assets/9682571/9985790/a8f0a0ce-6050-11e5-9d84-fe206a3547e1.png)
![admob_interstitial_error](https://cloud.githubusercontent.com/assets/9682571/9985795/b3cc628a-6050-11e5-893e-a776b05960d6.png)

**Comment by Prav92** [comment] 2016-01-08 12:43
i am also faces the same problem @floatinghotpot please helps us.
