### ISSUE TITLE
 Uncaught ReferenceError: AFMA_ReceiveMessage is not defined

### ISSUE THREAD

**Issue by dnish** [floatinghotpot/cordova-admob-pro#281] opened 2015-12-29 22:22 UTC
Hello,
I'm getting the error above in my console.log when I use an interstitial. The interstitial layer opens, but it is fully black (I can only see the close button). Just implemented it like this:

<code>AdMob.prepareInterstitial( {adId:"ca-.....", autoShow:true} );</code>

**Comment by floatinghotpot** [comment] 2015-12-30 00:18
See: https://groups.google.com/forum/m/#!category-topic/google-admob-ads-sdk/LVnmBbQd2l4

Can you reproduce the issue with good network, and give more details?

**Comment by dnish** [comment] 2015-12-30 00:24
Yeah, we've used our WLAN (100 Mbits) connection. The plugin was implemented into our Meteor Cordova app, which uses the Crosswalk plugin. The presentation of the first ad was successful (an Amazon ad), but all ads after that one failed with a black screen. I don't know if this has something to do with that issue, but normally we will see some "forex trading" ad campaign which uses a video interstitial. Maybe there are some issues with video ads?

**Comment by floatinghotpot** [comment] 2015-12-30 00:31
You can try configure your ad unit Id what type of ads to receive (in your admob portal), to see whether It happens to certain type of ads?

**Comment by dnish** [comment] 2015-12-30 10:00
After disabling "video", everything works fine. I'll later try it again with enabled video to be 100% sure that it has something to do with it.

**Comment by dnish** [comment] 2015-12-30 10:32
Okay, now it is working fine, also with activated video. I can't say why this error happened.

**Comment by floatinghotpot** [comment] 2015-12-30 10:49
I think it's caused by the ad content loaded from ad server, not by plugin. So I'll close this issue.

**Closed by floatinghotpot** 2015-12-30 10:49 UTC

**Comment by kpamansoor** [comment] 2016-07-22 01:05
I've faced same issue, it was the problem with loading time.I was trying to show adds before it loading completely. I changed the code like, loading settings in loading time and show adds in another page after some time. SO it works.
