### ISSUE TITLE
New API: getAdSettings()

### ISSUE THREAD

**Issue by floatinghotpot** [floatinghotpot/cordova-admob-pro#342] opened 2016-03-30 07:32 UTC
The advertising ID is a unique but user-resettable string identifier that lets ad networks and other apps anonymously identify a user.

See:

API from Google for Android:
http://developer.android.com/google/play-services/id.html

API from Apple for iOS:
https://developer.apple.com/library/ios/documentation/AdSupport/Reference/ASIdentifierManager_Ref/#//apple_ref/occ/clm/ASIdentifierManager/sharedManager

**Comment by floatinghotpot** [comment] 2016-04-03 08:54
Feature implemented, call `getAdSettings()` to get advertising Id.

```javascript
AdMob.getAdSettings(function(inf){
  // inf.adId;  // a UUID string
  // inf.adTrackingEnabled; // boolean
});
```

**Comment by berlindev** [comment] 2016-04-04 14:48
Thank you very much for this feature. 

It works on Android and iOS. 

It looks like there is a semantic/logic issue in Android. the function returns the not() of the value.

Steps to reproduce (on a google Nexus X5 marshmallow):
Settings->Google->Ads-> set OptOut button to 'off' -> got to the cordova app and get inf.adTrackingEnabled: false.

I am currently using a !(not) on the result and it totally works.

Thanks again.

**Comment by floatinghotpot** [comment] 2016-04-04 14:54
The value returned is result of this API:
`public boolean isLimitAdTrackingEnabled()`, Retrieves whether the user has limit ad tracking enabled or not.

How to understand this?

**Comment by berlindev** [comment] 2016-04-04 14:58
The way i understand it:
if isLimitAdTrackingEnabled() is false then inf.adTrackingEnabled should be true.
as the user did not ask to limit Ad Tracking and therefore atTracking Enabled should be true.

Makes sense or am i wrong?

Tom

**Comment by floatinghotpot** [comment] 2016-04-05 03:08
Yes, it does make sense. Will fix it soon.

**Comment by floatinghotpot** [comment] 2016-04-05 05:25
It's fixed, please update the dependent plugin `cordova-plugin-extension`.

**Comment by premathunga** [comment] 2016-08-24 14:27
please examples codes for interstitial ads "Events", 
Ex. closing the app, Back to home, 
thanks,

**Closed** 2016-12-28 12:35 UTC
Labels: New Feature
