### ISSUE TITLE
link error: GoogleMobileAds(GADGestureIdUtil.o) does not contain bitcode

### ISSUE THREAD

**Issue by ibewugb** [floatinghotpot/cordova-admob-pro#258] opened 2015-11-18 14:14 UTC
Hi, when packaging with XCode I get the following error:

ld: 'Foo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADGestureIdUtil.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by floatinghotpot** [comment] 2015-11-19 07:50
I find some clue here:
http://stackoverflow.com/questions/32073298/using-google-mobile-ads-sdk-v7-4-1-for-ios-googlemobileadssdkios-7-4-1-with-bi

But it's weird that the google admob iOS SDK here is already v7.5.2. 

Will double check and contact google admob team if still exists.

**Comment by floatinghotpot** [comment] 2015-11-19 07:51
BTW, which xcode version are you using?

**Comment by ibewugb** [comment] 2015-11-19 07:52
I'm using XCode 7.1

**Comment by floatinghotpot** [comment] 2015-11-19 09:54
I've reproduced the issue, will look into it. Stay tuned.

**Comment by ibewugb** [comment] 2015-11-19 10:02
Okay, thank you

**Comment by ibewugb** [comment] 2015-11-19 13:00
I updated to XCode 7.1.1 and Cordova 5.4.0 with cordova-ios@3.9.2, the error is still there.

**Comment by floatinghotpot** [comment] 2015-11-20 16:31
I've checked the Admob official support forum, and the truth is: bitcode support is not provided in admob sdk v7.5.2 yet, admob team is still working on it.

See:
https://groups.google.com/forum/#!topicsearchin/google-admob-ads-sdk/bitcode/google-admob-ads-sdk/ypBRdg5z0uM

So, let's just wait for their update, once they released new SDK, I will update the plugin immediately. Before it comes, please turn off bitcode in xcode build settings.

**Comment by ibewugb** [comment] 2015-11-20 17:03
Okay, thank you!

**Comment by floatinghotpot** [comment] 2015-11-20 17:04
Let's keep this issue open, I'd like to keep an eye on this.

**Comment by jmelvin** [comment] 2015-11-20 17:22
Thanks for leaving this issue open, Raymond.  I've been monitoring the download site, release notes, and google groups discussion on a daily basis...

https://developers.google.com/admob/ios/download
https://developers.google.com/admob/ios/rel-notes
https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/ypBRdg5z0uM

Google has been "working on" this issue for several months now.  This definitely affects the success of the AdMob plugin, especially if Apple begins rejecting apps due to this issue.  I'll be submitting shortly and will find out first hand.  8^0

Thanks for your efforts to support so many app developers with a great Cordova plugin for AdMob!!

**Comment by Sshuichi** [comment] 2016-01-10 16:15
Any news about this ?

**Comment by floatinghotpot** [comment] 2016-01-14 03:19
No luck. Google AdMob team is still working on this. 

I am keeping an eye on the official forum, if any new SDK released, it will be integrated with this plugin.

See:
https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/bitcode|sort:date/google-admob-ads-sdk/ypBRdg5z0uM/uOixAOM3CAAJ
https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/bitcode%7Csort:date/google-admob-ads-sdk/H1AXaT_mMcI/-F1bYRwJEAAJ

**Comment by floatinghotpot** [comment] 2016-02-09 03:50
Some great news. Bitcode will be supported in next release.

I got the info from Google AdMob official support forum the following news: 

> Good news - I have just been told that bitcode support will be available in our next SDK release.  Now I'm not authorized to comment on when we will release it, but if you look at our release cycle, you will see we tend to release a new SDK version fairly often.  So, watch out for that next release and you will be all set!

> Thanks,

> Vu Chau
Mobile Ads SDK Team

**Comment by zammbi** [comment] 2016-02-29 00:48
Version 7.7 now supports bitcode. 
https://developers.google.com/admob/ios/rel-notes

**Closed** 2016-02-29 03:19 UTC
Labels: Pending
