### ISSUE TITLE
Build failed with connectsdk

### ISSUE THREAD

**Issue by luclanet** [floatinghotpot/cordova-admob-pro#286] opened 2016-01-08 17:28 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
You can temporarily disable this error with android.enforceUniquePackageName=false
However, this is temporary and will be enforced in 1.0

BUILD FAILED

Total time: 43.45 secs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

C:\Apps\xxx\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                    ^
Error code 1 for command: cmd with args: /s /c "C:\Apps\xxx\platforms\android\gradlew cdvBuildDebug -b C:\Apps\xxx\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1

I'm using those plugins

com.google.admobsdk 6.12.2 "AdMob SDK for Android, iOS and WP8"
cordova-plugin-admob 2.2.0 "AdMob"
cordova-plugin-admobpro 2.10.0 "AdMob Plugin Pro"
cordova-plugin-app-preferences 0.7.3 "AppPreferences"
cordova-plugin-connectsdk 1.6.0 "Connect SDK"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-extension 1.2.3 "Cordova Plugin Extension"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-vibration 2.0.0 "Vibration"
cordova-plugin-whitelist 1.2.0 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"

**Comment by floatinghotpot** [comment] 2016-01-09 00:18
You use too many admob plugins, so they conflict with each other. You only need cordova-plugin-admobpro

**Comment by luclanet** [comment] 2016-01-09 01:57
It's the same

C:\Apps\xxx>cordova plugin list
cordova-plugin-admobpro 2.10.0 "AdMob Plugin Pro"
cordova-plugin-app-preferences 0.7.3 "AppPreferences"
cordova-plugin-connectsdk 1.6.0 "Connect SDK"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-extension 1.2.3 "Cordova Plugin Extension"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-vibration 2.0.0 "Vibration"
cordova-plugin-whitelist 1.2.0 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
You can temporarily disable this error with android.enforceUniquePackageName=false
However, this is temporary and will be enforced in 1.0

**Comment by floatinghotpot** [comment] 2016-01-09 02:45
The admobpro plugin depends on google play service library, which is published to maven by google, and refer to the most recent version, see:
https://github.com/floatinghotpot/cordova-admob-pro/blob/npm-admobpro/plugin.xml#L48

I check the source code of ConnectSDK, and found they also depends on google play service library but specify an exact gms version v7.8.0, 
https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/blob/master/Connect-SDK-Android/build.gradle#L73

I think that's the cause of conflict. 

I am quite curious that why they depends on an exact version? 
If any other plugin depends on another version, will it surely cause conflict?

**Comment by luclanet** [comment] 2016-01-09 03:15
Probally because they won't update all code to support last versions of play services. ConnectSDK looks so promising when I've used for the first time, now it looks abandoned.

**Comment by floatinghotpot** [comment] 2016-01-09 03:19
You can try asking them to update it, or forking to your own repo, then change the "7.8.0" to "+", then add plugin from your own github repo url.

**Comment by luclanet** [comment] 2016-01-09 03:26
I've already tryed but then went out a lot of errors of unknown functions and related...

**Comment by luclanet** [comment] 2016-01-09 03:28
I've also tried to change version on your plugin to match that on ConnectSDK but same error appear. (Error: more than one library with package name 'com.google.android.gms' )

**Comment by floatinghotpot** [comment] 2016-01-09 03:34
Do you find any other plugins in this project use gms?

Try removing ConnectSDK, to confirm the conflict is caused with it.

Or, you can try refresh the android platform things like this:
```bash
cordova platform remove android
cordova platform add android
```

**Comment by luclanet** [comment] 2016-01-09 12:57
Without ConnectSDK build was successful. I've already tried to remove and add back platform.

**Comment by orilux** [comment] 2016-01-15 02:01
Hi @luclanet, I ran into the same problem with these two plugins. I solved it by getting the ConnectSDK plugin to use the latest Google play services library. As you pointed out that will unleash a bunch of other build errors, but you can do a couple of other changes in the *build.gradle* file in the *Connect-SDK-Android* folder:

1. Change: *classpath 'com.android.tools.build:gradle:1.2.3'* to *classpath 'com.android.tools.build:gradle:1.3.0'*
2. Change *compileSdkVersion 22* to *compileSdkVersion 23*
3. Change *buildToolsVersion '22.0.1'* to *buildToolsVersion '23.0.2'*
4. Add *useLibrary  'org.apache.http.legacy'* on the next line (right before *packagingOptions*)
5. Change *compile 'com.google.android.gms:play-services-cast:7.8.0'* to *compile 'com.google.android.gms:play-services-cast:8.4.0'*

Hope this helps!

**Comment by floatinghotpot** [comment] 2016-01-15 02:39
It's recommended to change "com.google.android.gms:play-services-cast:8.4.0" to "com.google.android.gms:play-services-cast:+", which will always use the latest available version.

**Comment by luclanet** [comment] 2016-01-16 19:57
Hi @orilux, thanks for your message. It's really appreciated :)

I'm trying to fix another small problem that stops the build.

A problem occurred evaluating script.
> Could not find method useLibrary() for arguments [org.apache.http.legacy] on project ':cordova-plugin-connectsdk:Connect-SDK-Android'.

**Comment by orilux** [comment] 2016-01-18 02:34
Hi @luclanet, I updated my earlier post and added one more step to it (step 6). That should solve the problem you are having. Let me know if it works.

**Comment by orilux** [comment] 2016-01-18 03:14
@floatinghotpot, can we shake hands at:
```javascript
compile 'com.google.android.gms:play-services-cast:8.+'
```
? :)

**Comment by floatinghotpot** [comment] 2016-01-18 12:20
See:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/plugin.xml#L48

```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```

I think yours should be:
```bash
compile 'com.google.android.gms:play-services-cast:+'
```

**Comment by orilux** [comment] 2016-01-18 14:10
Yes, I agree that the two plugins will become incompatible again if there is a major version increase to 9.x.x, however the connectsdk plugin will likely break in the same way that it did when luclanet incremented from 7.x.x to 8.x.x.

**Comment by luclanet** [comment] 2016-01-18 22:14
YEEEEEEEEEEEEEEEEEEEEEE!!! It worked!

**Comment by luclanet** [comment] 2016-01-18 22:23
Thanks a lot to both of you @orilux @floatinghotpot :+1:

**Comment by floatinghotpot** [comment] 2016-01-19 02:14
Congratulations. And thanks to @orilux. Ok, then I close this issue tracker.

**Closed by floatinghotpot** 2016-01-19 02:14 UTC
Labels: Conflict with another plugin
