### ISSUE TITLE
Admob on footer

### ISSUE THREAD

**Issue by Rayz100** [floatinghotpot/cordova-admob-pro#87] opened 2015-02-19 08:35 UTC
Hi Ray,
Your tutorial was absolutely brilliant and yes I can display ads because you helped me. However, I have one problem with the following script 
```html
<button onclick="showAdMobBanner()">Show Banner Ad</button>
```

I want my adverts to appear without using the button onclick or body onload event, how do I do that so adverts appear on footer on pages I want them to be shown?

I am using Intel XDK for Andorid App development, thanks again mate.

**Comment by floatinghotpot** [comment] 2015-02-19 13:42
The onClick event is for demo only.

You can create and display banner when html page initialize, use body onload event, or document ready event.

**Comment by Rayz100** [comment] 2015-02-19 18:42
Thanks a lot mate, you are most welcome in your assistance. I know how to use body onload event but not so sure in using document ready event. Would you kindly give me an example so I can improve my understanding and also to know where to add document ready event? Thanks in advance.

**Comment by Rayz100** [comment] 2015-02-20 12:30
Mate tell me, what is the difference between the two cordova plugins
	Plugin ID: com.cranberrygame.phonegap.plugin.ad.admob 
	and this one	  
      Plugin ID: com.rjfun.cordova.plugin.admob

Your explanation on the above two would be greatly appreciated, thanks once again

**Comment by floatinghotpot** [comment] 2015-02-20 13:15
com.rjfun.cordova.plugin.admob is an early version, built little by little by a few guys.

com.google.cordova.admob is totally re-designed, much easier to use, with more features, tested and working with more tools, and documented in details. recommended.

cranberry is written by another guy, only used by construct2 users.

**Comment by floatinghotpot** [comment] 2015-02-20 13:25
if you use jquery, try ready event:
```javascript
$(document).ready(function(){
   document.addEventListener("deviceready", function(){
       // init and create banner here
   });
});
```

or, if not use jquery, then directly use javascript:
```javascript
document.addEventListener("deviceready", function(){
   // init and create banner here
});
```

**Comment by Rayz100** [comment] 2015-02-20 17:14
Wow, thanks a lot Ray. I really appreciate that. I don't have much right now but I am going to donate £10 to your paypal mate. I hope users on Ray's blog donate to keep his good work up. 

So guys please help this dude!!! His quiet helpful when you need help the most. Thanks a lot mate!!!

**Comment by floatinghotpot** [comment] 2015-02-23 00:28
it's my pleasure that you like my work and support. as the issue is resolved, i'd like to close this tracker.

**Closed by floatinghotpot** 2015-02-23 00:28 UTC

**Comment by Rayz100** [comment] 2015-02-26 15:50
Hi ya mate,
I am failing to find a link for paypal donation. I want to make that £10
donation to you please send me the link thanks.

On Mon, Feb 23, 2015 at 12:28 AM, Raymond Xie <notifications@github.com>
wrote:

> Closed #87 <https://github.com/floatinghotpot/cordova-admob-pro/issues/87>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/87#event-239867203>
> .
>



-- 
R.Otto
Bsc (Hons)

**Comment by floatinghotpot** [comment] 2015-02-27 00:54
PayPal: liming.xie@gmail.com, or rjfun.mobile@gmail.com, thank you for the support

**Comment by ridwanridiawan** [comment] 2015-06-09 20:08
hi ray.. 

I want my adverts to appear without using the button onclick


<!DOCTYPE html>
<html>
<head>
	<title>Hello AdMob</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" />
	<script src='cordova.js'></script>
	<script type="text/javascript">
		
        var onDeviceReady=function(){
            navigator.splashscreen.hide();
            initAdMob();
		};
		document.addEventListener("deviceready",onDeviceReady,false);
        
        function initAdMob(){
            if ( window.plugins && window.plugins.AdMob ) {
                var admob_key_banner = "ca-app-pub-2773616400896769/2194824337";
                var admob_key_interstitial = "ca-app-pub-2773616400896769/5840804739";
                window.plugins.AdMob.setOptions( {
                    publisherId: admob_key_banner,
                    bannerAtTop: false, // set to true, to put banner at top
                    overlap: false, // set to true, to allow banner overlap webview
                    offsetTopBar: true, // set to true to avoid ios7 status bar overlap                    
                    interstitialAdId: admob_key_interstitial,
                    autoShow: true, // autoshow intertitial Ad
                    isTesting: false // receiving test ad
                });
            } else {
                alert("AdMob plugin not ready");
            }
        }
        
        function showAdMobBanner(){
            window.plugins.AdMob.createBannerView();
        }
        
        function showAdMobInterstitial(){
            window.plugins.AdMob.createInterstitialView();
        }
        
	</script>
</head>
<body>
	<h1>Hello AdMob</h1>
    <br>
    <button onclick="showAdMobBanner()">Show Banner Ad</button>
    <br>
    <br>
    <br>
    <button onclick="showAdMobInterstitial()">Show Interstitial Ad</button>
</body>
</html>

**Comment by floatinghotpot** [comment] 2015-06-09 23:17
Here is a working demo:
https://github.com/floatinghotpot/admob-demo-game-pixi

Copy the content in demo folder to www, and build to run. 

Then only copy js/admob.js to your project and ref it in your index.html.
