### ISSUE TITLE
Looks Admob Pro not working well with new XDK 2496

### ISSUE THREAD

**Issue by zhao0057** [floatinghotpot/cordova-admob-pro#232] opened 2015-10-02 00:06 UTC
Crosswalk Android Build failed to load dependency.

**Comment by floatinghotpot** [comment] 2015-10-02 07:09
How do you reproduce the error? And, can you paste the log?

**Comment by zhao0057** [comment] 2015-10-02 08:17
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches
com.google.android.gms:play-services-ads:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-ads/
     Required by:
         :android:unspecified


Switch back to 2.9.6 and worked

**Comment by floatinghotpot** [comment] 2015-10-02 08:40
That's because Intel XDK does not support build with gradle. 

See:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

**Comment by cobbdb** [comment] 2015-10-02 09:20
I tried with both versions and sadly getting the same error for both:
```
Error: Plugin "" failed to install.
Error: Could not retrieve plugin dependencies for AdMob Plugin Pro'.
Error: Plugin AdMob Plugin Pro failed to install.
Plugin "org.apache.cordova.device" (0.2.13) installed.
Plugin "org.apache.cordova.vibration" (0.3.12) installed.
Plugin "com.adobe.plugins.GAPlugin" (2.4.0) installed.
Plugin "cordova-plugin-x-socialsharing" (5.0.3) installed.
Plugin "com.rjfun.cordova.extension" (1.1.4) installed.
Plugin "cordova-plugin-googleplayservices" (19.0.3) installed.
Plugin "org.apache.cordova.inappbrowser" (0.6.0) installed.
```

That's using `cordova-plugin-admob` v2.9.7

Looks like `com.google.cordova.admob` won't install anymore either due to an id mismatch with the google play library. Pretty sure I used to have it working with that.

Going to keep trying different combinations and will update once something works with latest XDK.

**Comment by cobbdb** [comment] 2015-10-02 09:21
Here's that google play services error btw:
```
Expected plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices".
```

**Comment by cobbdb** [comment] 2015-10-02 09:41
Success! Just got it working with latest (2496) XDK.. here's how:

1. Explicitly install 3rd party plugin `com.google.playservices`
2. Explicitly install 3rd party plugin `com.google.cordova.admob`

Build should work then. I tried all the other combinations of the other plugin ids and no luck.. sounds like due to the lack of Gradle support. Anyway, this is working fine for me now - just tested on a banner ad. Thanks @floatinghotpot for this awesome plugin!

**Comment by floatinghotpot** [comment] 2015-10-02 10:26
Please be aware that, Intel XDK is loading plugin from cordova plugin registry. But the registry is being deprecated, the official cordova CLI loads plugin from npm. The cordova plugin registry is now read-only and not allowed to update, I am not sure when the registry will be closed. 

As Intel XDK does not load plugin from npm yet. You can try another workaround:

1. download the following plugins to local folder by run ```npm install <plugin_name>```:
cordova-plugin-extension
cordova-plugin-googleplayservices
cordova-plugin-admob

2. Using Intel XDK to load the plugin from local folder.

**Comment by zhao0057** [comment] 2015-10-02 21:38
Thanks for the quick response! It works now.

**Comment by cobbdb** [comment] 2015-10-05 08:47
Hi @floatinghotpot I'm trying to get the npm install working for the facebook and iad mediation adapters since I plan on using those two networks, but I'm getting 404 not found. Do you know if there's another way to get those installed using XDK by chance?
cordova-plugin-admob-facebook
cordova-plugin-admob-iad

Just to make sure, those two plugins are required to use admob mediation right?

**Comment by cobbdb** [comment] 2015-10-06 04:07
Oh weird! Sorry please ignore that last post. I don't know what I was doing wrong yesterday, but I ran
$ npm i cordova-plugin-admob-iad
and it's installing just fine now for everything. However I found a much better fix for this XDK issue.

@zhao0057 @floatinghotpot It turns out that XDK (v2548) can move up to Cordova CLI v5.1.1 and install this plugin by just adding `cordova-plugin-admob` without doing any special. In Build Settings for the XDK project, just look in there for the drop-down to select which Crodova version to use. It took a little finagling, but I was finally able to get everything working now and see AdMob test ads working.
Hope that helps!

**Comment by cobbdb** [comment] 2015-10-06 04:10
The only thing to be aware of before rolling up your Cordova version is that there is currently a bug with XDK for some cordova plugins:
https://software.intel.com/en-us/forums/intel-xdk/topic/595059

I'm not seeing that with the iad mediation adapter, but I *am* seeing that with the facebook adapter.
That Intel post was from today, so hopefully they will have a fix for this issue sometime soon. In the mean time I will just stick with iad mediation and deal with facebook later.

**Closed** 2015-10-18 06:38 UTC

**Comment by innoserv** [comment] 2016-04-17 01:07
hello guys i build my app and i wanna add cordova admob but i don t know how to do it i have the plugin already added to my app so where should i put the code to rune admob into my app please help me
thx
