### ISSUE TITLE
Android tablet - Banner position

### ISSUE THREAD

**Issue by zabojad** [floatinghotpot/cordova-admob-pro#460] opened 2016-09-20 14:40 UTC
Here is the code I use to display a banner:

```
AdMob.createBanner({ adId : bannerId, autoShow : false, overlap : true, position : 8},function() {
        // ...
                AdMob.showBanner(8);
    },function() {
        // ...  });

```

The problem is that the banner displays in the bottom left side of the screen, not bottom center... Bug ?

**Comment by floatinghotpot** [comment] 2017-04-01 04:15
not a bug of plugin, it's the SDK behavior if use adType BANNER or DFP banner.

use AdMob and adType SMART_BANNER, it will be in bottom center.

**Closed by floatinghotpot** 2017-04-01 04:15 UTC
