### ISSUE TITLE
"kindle://home" - error: "This app is not allowed to query for scheme kindle" IOS 9

### ISSUE THREAD

**Issue by Jorybraun** [floatinghotpot/cordova-admob-pro#224] opened 2015-09-17 17:07 UTC
how to i resolve

"kindle://home" - error: "This app is not allowed to query for scheme kindle"

**Comment by floatinghotpot** [comment] 2015-09-17 17:18
how to reproduce this error message? any screenshot?

**Comment by floatinghotpot** [comment] 2015-09-18 01:07
Frankly speaking, this is a good issue report, as I did not see any connection with this plugin.

A good report should include:
1. steps to reproduce the error.
2. evidence, like logs, screenshots.

**Comment by bastaware** [comment] 2015-09-22 11:08
See this

http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

**Comment by RonnySchleicher** [comment] 2015-09-29 15:56
##### Steps to reproduce
1. create a PhoneGap Application on your MAC like PhoneGap Documentation
2 Open the PhoneGap project with X-Code
3. connect yout iPhone-Device on yout iMac
4. Run the PhoneGap application on yout iPhone
5. in The X-Code Log window occurs the described error message. See in following screenshoot:

**Note:** The error messages occurs only with a enabled AdMob-Plugin.

![image](https://cloud.githubusercontent.com/assets/1914203/10169845/434c9802-66d3-11e5-983f-bf91ec8c6182.png)

**Comment by RonnySchleicher** [comment] 2015-09-29 15:59
#### Used Software Versions
cordova VERSION = "4.1.1"
"cordova-plugin-whitelist": "1.0.0",
"cordova-plugin-device-motion": "1.1.1",
"cordova-plugin-media-capture": "1.0.1",
"cordova-plugin-device-orientation": "1.0.1",
"cordova-plugin-network-information": "1.0.1",
"cordova-plugin-contacts": "1.1.0",
"cordova-plugin-device": "1.0.1",
"cordova-plugin-battery-status": "1.1.0",
"cordova-plugin-file-transfer": "1.2.1",
"cordova-plugin-geolocation": "1.0.1",
"cordova-plugin-globalization": "1.0.1",
"cordova-plugin-inappbrowser": "1.0.1",
"cordova-plugin-media": "1.0.1",
"cordova-plugin-dialogs": "1.1.1",
"cordova-plugin-vibration": "1.2.0",
"cordova-plugin-splashscreen": "2.1.0",
"cordova-plugin-console": "1.0.1",
"cordova-plugin-statusbar": "1.0.1",
"cordova-plugin-admobpro": "2.9.2",
"cordova-plugin-file": "3.0.0",
"cordova-plugin-extension": "1.1.4"

#### Used Device
iPhone 4S with iOS 9.0.1

**Comment by justin-taylor** [comment] 2015-09-30 18:49
:+1: 

This appears to be an issue with iOS 9s canOpenUrl changes and the version of the Admob framework packaged with this plugin (see [https://groups.google.com/forum/#!topic/google-admob-ads-sdk/IYZpEfbQEU8](https://groups.google.com/forum/#!topic/google-admob-ads-sdk/IYZpEfbQEU8)). 

Manually updating the framework to [version 7.5.0](https://developers.google.com/admob/ios/download?hl=en) seems to be a temp fix for the issue.

**Comment by floatinghotpot** [comment] 2015-10-02 07:06
yes, you are correct. google team has fixed the bug in v7.5.0, and now the plugin has been updated with the v7.5.0 sdk. you can update the plugin to enjoy the benefit now.

**Comment by RonnySchleicher** [comment] 2015-10-05 15:46
'Bug' is fixed in the new AdMob Plugin Version 2.9.8.
Thank you!

**Closed** 2015-10-06 11:16 UTC
