### ISSUE TITLE
Android app showing err like error:0, reason:Internal error, adNetwork:AdMOB,adType:banner,adEvent:onAdFailLoad

### ISSUE THREAD

**Issue by shamimnasir** [floatinghotpot/cordova-admob-pro#496] opened 2017-01-05 23:07 UTC
Hello Floating, 

I have made many apps so far using the exact same code. But, today, I failed. 

Can you please check the code and help me on this issue? 

<img width="860" alt="screen shot 2017-01-06 at 5 06 02 am" src="https://cloud.githubusercontent.com/assets/7089205/21701096/f25b94e8-d3cd-11e6-892b-8c3bbbb405eb.png">

My Code on the Index.html page:

```html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>চুলের যত্ন - Hair Care Bangla</title>
	
	<meta name="description" content="You will get detailed tips on styling, careing and polishing your hairs in Bangla." />
	
	<meta name="keywords" content="hair care bangla, bangla culer jotno, chuler jotno, hair bangla, bangla hair care tips," />
	<link rel="stylesheet" href="css/jquery.mobile-1.4.2.min.css">
    <link rel="stylesheet" href="css/style.css">

	<script src="js/jquery.js"></script>	
	<script src="js/jquery.mobile-1.4.2.min.js"></script>
	 <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"/>
  <script type="text/javascript" src="cordova.js"></script>
  <script type="text/javascript" src="jquery-1.9.js"></script>
  <script>
  // fix wp8 view port issue, see:
  // https://github.com/floatinghotpot/cordova-admob-pro/issues/109
  // https://coderwall.com/p/zk_2la/responsive-design-in-ie-10-on-windows-phone-8
  // http://stackoverflow.com/questions/24007577/windows-phone-8-viewport-issue
(function() {
  if ("-ms-user-select" in document.documentElement.style && navigator.userAgent.match(/IEMobile\/10\.0/)) {
    var msViewportStyle = document.createElement("style");
    msViewportStyle.appendChild(
      document.createTextNode("@-ms-viewport{width:auto!important}")
    );
    document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
  }
})();
</script>
  
</head>

<body>
<script>
  // place our admob ad unit id here
  var admobid = {};
  if( /(android)/i.test(navigator.userAgent) ) {
    admobid = { // for Android
      banner: 'ca-app-pub-7964685388872167/3178988739',
      interstitial: 'ca-app-pub-7964685388872167/3178988739'
    };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
       banner: 'ca-app-pub-7964685388872167/3178988739',
      interstitial: 'ca-app-pub-7964685388872167/3178988739'
    };
  } else {
    admobid = { // for Windows Phone
       banner: 'ca-app-pub-7964685388872167/3178988739',
      interstitial: 'ca-app-pub-7964685388872167/3178988739'
    };
  }
  function createSelectedBanner(){
    if(AdMob) AdMob.createBanner({
      adId: admobid.banner,
      overlap: $('#overlap').is(':checked'),
      offsetTopBar: $('#offsetTopBar').is(':checked'),
      adSize: $('#adSize').val(),
      position: $('#adPosition').val(),
    });
  }

  function showBannerAtPosition(){
    if(AdMob) AdMob.showBanner( $('#adPosition').val() );
  }

  function onDeviceReady() {
    if (! AdMob) { alert( 'admob plugin not ready' ); return; }

    initAd();

    // display a banner at startup
    createSelectedBanner();
  }

  function initAd(){
    AdMob.getAdSettings(function(info){
      console.log('adId: ' + info.adId + '\n' + 'adTrackingEnabled: ' + info.adTrackingEnabled);
    }, function(){
      console.log('failed to get user ad settings');
    });

    AdMob.setOptions({
      // adSize: 'SMART_BANNER',
      position: AdMob.AD_POSITION.BOTTOM_CENTER,
      bgColor: 'black', // color name, or '#RRGGBB'
      // autoShow: true // auto show interstitial ad when loaded, set to false if prepare/show
      // offsetTopBar: false, // avoid overlapped by status bar, for iOS7+
    });

    // new events, with variable to differentiate: adNetwork, adType, adEvent
    $(document).on('onAdFailLoad', function(e){
      // when jquery used, it will hijack the event, so we have to get data from original event
      if(typeof e.originalEvent !== 'undefined') e = e.originalEvent;
      var data = e.detail || e.data || e;

      alert('error: ' + data.error +
          ', reason: ' + data.reason +
          ', adNetwork:' + data.adNetwork +
          ', adType:' + data.adType +
          ', adEvent:' + data.adEvent); // adType: 'banner', 'interstitial', etc.
    });
    $(document).on('onAdLoaded', function(e){
    });
    $(document).on('onAdPresent', function(e){
    });
    $(document).on('onAdLeaveApp', function(e){
    });
    $(document).on('onAdDismiss', function(e){
    });

    $('#btn_create').click(createSelectedBanner);
    $('#btn_remove').click(function(){
      AdMob.removeBanner();
    });

    $('#btn_show').click(showBannerAtPosition);
    $('#btn_hide').click(function(){
      AdMob.hideBanner();
    });

    // test interstitial ad
    $('#btn_prepare').click(function(){
      AdMob.prepareInterstitial({
        adId:admobid.interstitial,
        autoShow: $('#autoshow').is(':checked'),
      });
    });

    $('#btn_showfull').click(function(){
      AdMob.showInterstitial();
    });

    // test case #283, https://github.com/floatinghotpot/cordova-admob-pro/issues/283
    $(document).on('resume', function(){
      AdMob.showInterstitial();
    });
  }

  // test the webview resized properly
  $(window).resize(function(){
    $('#textinfo').html('web view: ' + $(window).width() + " x " + $(window).height());
  });

  $(document).ready(function(){
    // on mobile device, we must wait the 'deviceready' event fired by cordova
    if(/(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent)) {
      document.addEventListener('deviceready', onDeviceReady, false);
    } else {
      onDeviceReady();
    }
  });

</script>

<div data-role="page" id="home">
```

**Comment by faisalthaheem** [comment] 2017-01-06 04:09
Having the same problem.

**Comment by faisalthaheem** [comment] 2017-01-06 13:40
After wasting hours, the problem was fixed by connecting to internet via a different ISP. For some weird reason internal server error was returned on my data package. Once I connected using DSL over wifi ads starting showing up again, and they are still showing after restarting the app and switching back to the data connection.

**Comment by izacGaldino** [comment] 2017-01-19 11:58
Hello I'm having the same problem a few days, have you found a solution?

Screenshot:

![screenshot_2017-01-19-08-44-37](https://cloud.githubusercontent.com/assets/18285319/22105994/cfa25a76-de2d-11e6-8a91-ca6783bec8b5.png)

**Comment by v007prajapati** [comment] 2017-01-22 10:46
Having the same problem 

error: 0, reason: Internal error, adNetwork:AdMob, adType:banner, adEvent:onAdFailLoad

app works on test mode but not in live mode.

**Comment by floatinghotpot** [comment] 2017-01-26 07:26
If AdMob works on test mode, it means the plugin and SDK working well. 

Please check your ad unit id status.

**Comment by v007prajapati** [comment] 2017-01-28 03:35
Hi, on Admob dashboard I didn't see anything which will indicate that the ad units are blocked or disabled.
However I tried different plugin (https://github.com/appfeel/admob-google-cordova/) and the ads are not working both in testing as well as in live mode

**Comment by floatinghotpot** [comment] 2017-01-30 03:15
Please try following commands to verify the plugin itself working well in your environment:
```bash
plugin-verify cordova-plugin-pro android
```

If you can see a testing ad on simulator, then the plugin works well, then the only thing to do is to double check your ad unit id.

**Comment by floatinghotpot** [comment] 2017-02-01 02:28
```javascript
if( /(android)/i.test(navigator.userAgent) ) {
    admobid = { // for Android
      banner: 'ca-app-pub-7964685388872167/3178988739',
      interstitial: 'ca-app-pub-7964685388872167/3178988739'
    };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
       banner: 'ca-app-pub-7964685388872167/3178988739',
      interstitial: 'ca-app-pub-7964685388872167/3178988739'
    };
  } else {
    admobid = { // for Windows Phone
       banner: 'ca-app-pub-7964685388872167/3178988739',
      interstitial: 'ca-app-pub-7964685388872167/3178988739'
    };
  }
```

I notice that you are using the SAME ad unit id for all !!!

Please be aware that, 
1. in AdMob portal, you need create app for different platform, then create banner ad unit id and interstitial ad unit id.
2. use the ad unit id created for android, in android app only; use the ad unit created for ios, in ios app only.
3. use the banner ad unit id for banner only, use interstitial ad unit for interstitial only.

**Comment by utilityexpertservices** [comment] 2017-02-12 20:23
I am also having the similar issue. The solution i found is if i change the app id while building the app, the add are showing up But i cannot upload the app with a different app id in play store. I seems the admob is not able to verify the app id . Do we need to save the app id or something like this so that admob can verify the app id?

**Comment by floatinghotpot** [comment] 2017-02-13 07:06
The error event 'onAdFailedLoad' is returned by the AdMob SDK.

If you change app id then it works, it means that there might be something wrong with your app id. 

Is it too long and admob service does not allow it? Just guess.

**Comment by utilityexpertservices** [comment] 2017-02-20 03:27
App id is not too long.Even longer than present app id works. What wrong
can it be? not able to find any solution at present. Request your help.

regards,
Utility Expert

**Comment by floatinghotpot** [comment] 2017-02-28 04:52
Then this non-working app id must have something wrong. As we both cannot find the root cause, change to a new and working app id.

**Closed by floatinghotpot** 2017-02-28 04:52 UTC
